# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gardalte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gardalte/proprietary/vendor/firmware/bcm4334.hcd:system/vendor/firmware/bcm4334.hcd \
    vendor/samsung/gardalte/proprietary/vendor/firmware/BT_FW_VER_BCM4334B0_002.001.013.1810.2178_Garda_ORC.hcd:system/vendor/firmware/BT_FW_VER_BCM4334B0_002.001.013.1810.2178_Garda_ORC.hcd \
    vendor/samsung/gardalte/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/hw/camera.universal3470.so:system/vendor/lib/hw/camera.universal3470.so \
    vendor/samsung/gardalte/proprietary/etc/srm.bin:system/etc/srm.bin \
    vendor/samsung/gardalte/proprietary/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
    vendor/samsung/gardalte/proprietary/lib/libhdcp2.so:system/lib/libhdcp2.so \
    vendor/samsung/gardalte/proprietary/lib/libstagefright_hdcp.so:system/lib/libstagefright_hdcp.so \
    vendor/samsung/gardalte/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/gardalte/proprietary/bin/gps.cer:system/bin/gps.cer \
    vendor/samsung/gardalte/proprietary/bin/gpsd:system/bin/gpsd \
    vendor/samsung/gardalte/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/gardalte/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/gardalte/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/gardalte/proprietary/lib/libwrappergps.so:system/lib/libwrappergps.so \
    vendor/samsung/gardalte/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/gardalte/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/gardalte/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/gardalte/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/gardalte/proprietary/lib/hw/gralloc.exynos3.so:system/lib/hw/gralloc.exynos3.so \
    vendor/samsung/gardalte/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/gardalte/proprietary/lib/libdisplay.so:system/lib/libdisplay.so \
    vendor/samsung/gardalte/proprietary/lib/libdisplaymodule.so:system/lib/libdisplaymodule.so \
    vendor/samsung/gardalte/proprietary/lib/libexynosfimc.so:system/lib/libexynosfimc.so \
    vendor/samsung/gardalte/proprietary/lib/libExynosHWCService.so:system/lib/libExynosHWCService.so \
    vendor/samsung/gardalte/proprietary/lib/libExynosIPService.so:system/lib/libExynosIPService.so \
    vendor/samsung/gardalte/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/gardalte/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/gardalte/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/gardalte/proprietary/lib/libhdmimodule.so:system/lib/libhdmimodule.so \
    vendor/samsung/gardalte/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/gardalte/proprietary/lib/libhwcutilsmodule.so:system/lib/libhwcutilsmodule.so \
    vendor/samsung/gardalte/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/gardalte/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/gardalte/proprietary/lib/libmpp.so:system/lib/libmpp.so \
    vendor/samsung/gardalte/proprietary/lib/libvirtualdisplaymodule.so:system/lib/libvirtualdisplaymodule.so \
    vendor/samsung/gardalte/proprietary/lib/libvirtualdisplay.so:system/lib/libvirtualdisplay.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/hw/hwcomposer.exynos3.so:system/vendor/lib/hw/hwcomposer.exynos3.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/hw/keystore.exynos3.so:system/vendor/lib/hw/keystore.exynos3.so \
    vendor/samsung/gardalte/proprietary/vendor/lib/hw/lights.exynos3.so:system/vendor/lib/hw/lights.exynos3.so \
    vendor/samsung/gardalte/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/gardalte/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/gardalte/proprietary/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/gardalte/proprietary/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/gardalte/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/gardalte/proprietary/vendor/firmware/fimc_is_fw2.bin:system/vendor/firmware/fimc_is_fw2.bin \
    vendor/samsung/gardalte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/gardalte/proprietary/vendor/firmware/setfile_4h5.bin:system/vendor/firmware/setfile_4h5.bin \
    vendor/samsung/gardalte/proprietary/vendor/firmware/setfile_6a3.bin:system/vendor/firmware/setfile_6a3.bin \
    vendor/samsung/gardalte/proprietary/vendor/firmware/setfile_6b2.bin:system/vendor/firmware/setfile_6b2.bin \
    vendor/samsung/gardalte/proprietary/bin/mcDriverDaemon:system/bin/mcDriverDaemon \
    vendor/samsung/gardalte/proprietary/app/FFFFFFFF000000000000000000000001.drbin:system/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/00060308060501020000000000000000.tlbin:system/app/mcRegistry/00060308060501020000000000000000.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/02010000080300030000000000000000.tlbin:system/app/mcRegistry/02010000080300030000000000000000.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/03010000080300030000000000000000.tlbin:system/app/mcRegistry/03010000080300030000000000000000.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/07010000000000000000000000000000.tlbin:system/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/07060000000000000000000000000000.tlbin:system/app/mcRegistry/07060000000000000000000000000000.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff000000000000000000000004.tlbin:system/app/mcRegistry/ffffffff000000000000000000000004.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff000000000000000000000005.tlbin:system/app/mcRegistry/ffffffff000000000000000000000005.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff000000000000000000000009.tlbin:system/app/mcRegistry/ffffffff000000000000000000000009.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff00000000000000000000000c.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000c.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff00000000000000000000000d.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000d.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff00000000000000000000000e.tlbin:system/app/mcRegistry/ffffffff00000000000000000000000e.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffff000000000000000000000018.tlbin:system/app/mcRegistry/ffffffff000000000000000000000018.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffffd00000000000000000000004.tlbin:system/app/mcRegistry/ffffffffd00000000000000000000004.tlbin \
    vendor/samsung/gardalte/proprietary/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin:system/app/mcRegistry/ffffffffd0000000000000000000000e.tlbin \
    vendor/samsung/gardalte/proprietary/lib/libgdmcprov.so:system/lib/libgdmcprov.so \
    vendor/samsung/gardalte/proprietary/lib/libMcClient.so:system/lib/libMcClient.so \
    vendor/samsung/gardalte/proprietary/lib/libMcRegistry.so:system/lib/libMcRegistry.so \
    vendor/samsung/gardalte/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/gardalte/proprietary/bin/IPSecService:system/bin/IPSecService \
    vendor/samsung/gardalte/proprietary/csc/sales_code.dat:system/csc/sales_code.dat \
    vendor/samsung/gardalte/proprietary/etc/plmn_delta.bin:system/etc/plmn_delta.bin \
    vendor/samsung/gardalte/proprietary/etc/plmn_se13.bin:system/etc/plmn_se13.bin \
    vendor/samsung/gardalte/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/gardalte/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/gardalte/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/gardalte/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/gardalte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/gardalte/proprietary/etc/PDC.ini:system/etc/PDC.ini \
    vendor/samsung/gardalte/proprietary/lib/hw/sensors.universal3470.so:system/lib/hw/sensors.universal3470.so \
    vendor/samsung/gardalte/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/gardalte/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/gardalte/proprietary/etc/wifi/bcmdhd_apsta.bin_b2:system/etc/wifi/bcmdhd_apsta.bin_b2 \
    vendor/samsung/gardalte/proprietary/etc/wifi/bcmdhd_p2p.bin_b2:system/etc/wifi/bcmdhd_p2p.bin_b2 \
    vendor/samsung/gardalte/proprietary/etc/wifi/bcmdhd_sta.bin_b2:system/etc/wifi/bcmdhd_sta.bin_b2 \
    vendor/samsung/gardalte/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt
